AllCops:
  NewCops: enable

Style/AndOr:
  Enabled: false
  
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/EndOfLine:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 25

Style/EndOfLine:
 EnforcedStyle: crlf
