AllCops:
  NewCops: enable

Style/AndOr:
  Enabled: false
  
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/EndOfLine:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 45

Style/EndOfLine:
 EnforcedStyle: crlf

Metrics/BlockLength:
  Exclude:
    - "spec/**/*_spec.rb"